app:
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server"
  ports:
    - 3000:3000
  links:
    - mysql
  volumes:
    - './:/app'

mysql:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  restart: always
  environment:
    - MYSQL_ROOT_USERNAME=root
    - MYSQL_ROOT_PASSWORD=root